version: 0.0
os: linux
files:
  - source: /api
    destination: /var/www/vhosts/stg-api-games.sonyliv.com/httpdocs/
  - source: /cms
    destination: /var/www/vhosts/stg-cms-games.sonyliv.com/httpdocs/
hooks:
  BeforeInstall:
    - location: backup_files
      timeout: 300
      runas: root
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
      
