#!/bin/bash
#cp -r /var/www/gamesmela/html/* /var/tmp/httpdocs
#rm -rf /var/www/gamesmela/html/*
rsync -a /var/www/gamesmela/html/* /var/tmp/httpdocs/
#cp -r /var/www/gamesmela/html/* /var/tmp/httpdocs/
